### PR TITLE
FOGL-1625 - Fixed tests

### PR DESCRIPTION
**Pull request by amarendra-dianomic**

### CODE REVIEW

**Review by ashish-jabble — CHANGES_REQUESTED** [review]
Out of 14 tests 5 are failed due to  `missing 1 required positional argument: 'protocol'`
for `payload = StreamReader(loop=loop)`

```
test/test_http_south.py::TestHttpSouthIngest::test_render_post_reading_ok[pyloop] FAILED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_sensor_values_ok[pyloop] FAILED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_invalid_payload[pyloop] FAILED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_reading_missing_delimiter[pyloop] FAILED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_reading_not_dict[pyloop] FAILED

=== FAILURES ===
/home/foglamp/Development/foglamp-south-http/test/test_http_south.py:62: TypeError: __init__() missing 1 required positional argument: 'protocol'
```

**Comment by amarendra-dianomic** [comment]
@ashish-jabble seems to some environment error as I am unable to reproduce the error:
```
foglamp-south-http (FOGL-1625) $ pytest -s -vv test/test_http_south.py
============================================================== test session starts ==============================================================
platform linux -- Python 3.5.3+, pytest-3.6.0, py-1.5.4, pluggy-0.6.0 -- /usr/bin/python3.5
cachedir: .pytest_cache
rootdir: /home/asinha/dev/foglamp-south-http, inifile:
plugins: mock-1.10.0, cov-2.5.1, asyncio-0.8.0, allure-adaptor-1.7.10, aiohttp-0.3.0
collected 14 items                                                                                                                              

test/test_http_south.py::test_plugin_contract PASSED
test/test_http_south.py::test_plugin_info PASSED
test/test_http_south.py::test_plugin_init PASSED
test/test_http_south.py::test_plugin_start PASSED
test/test_http_south.py::test_plugin_start_exception PASSED
test/test_http_south.py::test_plugin_reconfigure PASSED
test/test_http_south.py::test_plugin__stop[pyloop] PASSED
test/test_http_south.py::test_plugin_shutdown PASSED
test/test_http_south.py::test_plugin_shutdown_error[pyloop] SKIPPED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_reading_ok[pyloop] PASSED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_sensor_values_ok[pyloop] PASSED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_invalid_payload[pyloop] PASSED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_reading_missing_delimiter[pyloop] PASSED
test/test_http_south.py::TestHttpSouthIngest::test_render_post_reading_not_dict[pyloop] PASSED

===================================================== 13 passed, 1 skipped in 0.24 seconds ======================================================

```

**Review by praveen-garg — CHANGES_REQUESTED** [review]
@amarendra-dianomic  remove the import `from foglamp.services.south.ingest import Ingest ` as requested in JIRA

**Review by ashish-jabble — APPROVED** [review]
After `.local` and `.cache` dir removal from my environment and set up again. All tests are passing.

**Review by praveen-garg — APPROVED** [review]
Had to remove .local and .cache directory from ~ (root).

**Pull request merged**
